server:
  port: 9001

spring:
  application:
    name: school-service
  cloud:
    consul:
      host: 192.168.1.221
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        preferIpAddress: true

management:
  info:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
