server:
  port: 9002

spring:
  application:
    name: student-service
  cloud:
    consul:
      host: 192.168.1.221
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
#        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 15s
        preferIpAddress: true

management:
  info:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"

