server:
  port: 9090

spring:
  application:
    name: discover-service
  cloud:
    consul:
      host: 192.168.1.221
      port: 8500
      discovery:
        enabled: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        preferIpAddress: true

management:
  info:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"

